version: '3.7'
services:
  mysql:
    image: mysql:8.0.19
    ports: ['3306:3306']
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dev_test
      - MYSQL_USER=dev_test
      - MYSQL_PASSWORD=dev_test
  php:
    build: ./docker/php
    ports: ['9000:9000']
    links:
      - mysql
    volumes:
      - ./:/var/www/html:cached
  nginx:
    build: ./docker/nginx
    ports:
      - '80:80'
      - '443:443'
    links:
      - php
    depends_on:
      - php
    volumes:
      - ./:/var/www/html:cached
  node:
    image: node:14
    volumes:
      - ./:/app:cached
    working_dir: /app
    command: sh -c "yarn install && yarn encore dev --watch"
